echo compiling...
g++ mazeSolver.cpp -o mazeSolver
echo running program...
echo
./mazeSolver | tee MazeOutput.txt
echo compiling latex document...
pdflatex MazeSolver.tex
echo copying documents...
echo opening pdf...
open amortization.pdf
echo copying documents...
cp -a mazeSolver.cpp projectExport
cp -a MazeOutput.txt projectExport
cp -a MazeSolver.pdf projectExport
echo moving junk...
mv mazeSolver.log mazeSolver.aux mazeSolver.toc bin
echo zipping folder...
zip -r HamiltonCousinoProj4.zip projectExport
echo project compile finished!
